module.exports = {
  content: ["./src/**/*.{vue,js,ts}"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["light"],
          primary: "#ff6600",
          "primary-focus": "#ff6600",
          "primary-content": "#ffffff",
          secondary: "#ff6600",
          accent: "#ff6600",
          neutral: "#000000",
          "base-100": "#ffffff",
          "base-200": "#ffffff",
          "base-300": "#ffffff",
          "base-content": "#000000",
          info: "#ff6600",
          success: "#ff6600",
          warning: "#ff6600",
          error: "#ff6600",
        },
      },
      {
        dark: {
          ...require("daisyui/src/theming/themes")["dark"],
          primary: "#ff6600",
          "primary-focus": "#ff6600",
          "primary-content": "#ffffff",
          secondary: "#ff6600",
          accent: "#ff6600",
          neutral: "#ffffff",
          "base-100": "#000000",
          "base-200": "#000000",
          "base-300": "#000000",
          "base-content": "#ffffff",
          info: "#ff6600",
          success: "#ff6600",
          warning: "#ff6600",
          error: "#ff6600",
        },
      },
    ],
    defaultTheme: "light",
  },
};
